set ts=2
set ignorecase
set tabstop=2
set expandtab

" show line numbers
set number

" exclude certain common folders from wildcard expansion (
" during search, etc.)
set wildignore+=venv/*

syntax on


""""""""""""""""""""""""""""""""""
" vim plugins (managed by plug.vim
"
" per https://github.com/junegunn/vim-plug
" - `:PlugInstall` to install plugins
"
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()

