set ts=2
set ignorecase
set tabstop=2
set expandtab

" show line numbers
set number
" show column number
set ruler

" exclude certain common folders from wildcard expansion (
" during search, etc.)
set wildignore+=venv/*

syntax on

" bid ctrl p to `Files`
map <c-p> :Files<cr>

" Auto remove trailing white space on save
autocmd BufWritePre * %s/\s\+$//e

""""""""""""""""""""""""""""""""""
" vim plugins (managed by plug.vim
"
" per https://github.com/junegunn/vim-plug
" - `:PlugInstall` to install plugins
"
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
" fzf and Rg requires `brew install fzf` & `brew install ripgrep`
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
" vim-gutentags requires ctags installed from homebrew - macos native version
" does not work
Plug 'ludovicchabant/vim-gutentags'
call plug#end()

let g:gutentags_ctags_exclude = [
      \ '*.git',
      \ '*/venv/*',
      \ 'dist',
      \ 'bin',
      \ '*/node_modules/*',
      \ ]

let g:ctrlp_custom_ignore = 'node_modules\|venv\' 

